package com.leiqjl;

/**
 * 389. Find the Difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        char c = t.charAt(t.length()-1);
        for (int i = 0; i < s.length(); i++) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }

    public char findTheDifference1(String s, String t) {
        int a = t.charAt(t.length()-1);
        for (int i = 0; i < s.length(); i++) {
            a = a + t.charAt(i) - s.charAt(i);
        }
        return (char) a;
    }

}
